import { User } from "@/components/pagecomponents/userspage/EditUserProfile";

export const usersData = [
  {
    id: 1,
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    firstName: "John",
    lastName: "Doe",
    fullName: "John Doe",
    role: "Admin",
    email: "john.doe@example.com",
    phoneNumber: "1234567890",
    address: "123 Main St, Anytown, USA",
    country: "USA",
    dob: "1990-01-01",
    gender: "male",
    documents: [],
    lastActive: "2023-07-01",
    status: "Active",
  },
  {
    id: 2,
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    firstName: "Jane",
    lastName: "Smith",
    fullName: "Jane Smith",
    role: "User",
    email: "jane.smith@example.com",
    phoneNumber: "0987654321",
    address: "456 Elm St, Othertown, USA",
    country: "USA",
    dob: "1985-05-15",
    gender: "female",
    documents: [],
    lastActive: "2023-06-28",
    status: "Inactive",
  },
  {
    id: 3,
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    firstName: "Bob",
    lastName: "Johnson",
    fullName: "Bob Johnson",
    role: "Moderator",
    email: "bob.johnson@example.com",
    phoneNumber: "1122334455",
    address: "789 Oak St, Sometown, USA",
    country: "USA",
    dob: "1975-08-20",
    gender: "male",
    documents: [],
    lastActive: "2023-06-30",
    status: "Active",
  },
  {
    id: 4,
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    firstName: "Alice",
    lastName: "Davis",
    fullName: "Alice Davis",
    role: "User",
    email: "alice.davis@example.com",
    phoneNumber: "6677889900",
    address: "101 Pine St, Yourtown, USA",
    country: "USA",
    dob: "1992-11-25",
    gender: "female",
    documents: [],
    lastActive: "2023-06-29",
    status: "Active",
  },
  {
    id: 5,
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    firstName: "Charlie",
    lastName: "Brown",
    fullName: "Charlie Brown",
    role: "Admin",
    email: "charlie.brown@example.com",
    phoneNumber: "2233445566",
    address: "202 Maple St, Mytown, USA",
    country: "USA",
    dob: "1980-02-14",
    gender: "male",
    documents: [],
    lastActive: "2023-06-27",
    status: "Inactive",
  },
  {
    id: 6,
    image: "https://randomuser.me/api/portraits/men/6.jpg",
    firstName: "Michael",
    lastName: "Johnson",
    fullName: "Michael Johnson",
    role: "User",
    email: "michael.johnson@example.com",
    phoneNumber: "3344556677",
    address: "303 Birch St, Anycity, USA",
    country: "USA",
    dob: "1988-07-30",
    gender: "male",
    documents: [],
    lastActive: "2023-07-02",
    status: "Active",
  },
  {
    id: 7,
    image: "https://randomuser.me/api/portraits/women/7.jpg",
    firstName: "Jessica",
    lastName: "Williams",
    fullName: "Jessica Williams",
    role: "Moderator",
    email: "jessica.williams@example.com",
    phoneNumber: "4455667788",
    address: "404 Cedar St, Othercity, USA",
    country: "USA",
    dob: "1995-04-10",
    gender: "female",
    documents: [],
    lastActive: "2023-06-25",
    status: "Inactive",
  },
  {
    id: 8,
    image: "https://randomuser.me/api/portraits/men/8.jpg",
    firstName: "William",
    lastName: "Brown",
    fullName: "William Brown",
    role: "User",
    email: "william.brown@example.com",
    phoneNumber: "5566778899",
    address: "505 Spruce St, Somecity, USA",
    country: "USA",
    dob: "1991-03-22",
    gender: "male",
    documents: [],
    lastActive: "2023-06-26",
    status: "Active",
  },
  {
    id: 9,
    image: "https://randomuser.me/api/portraits/women/9.jpg",
    firstName: "Olivia",
    lastName: "Garcia",
    fullName: "Olivia Garcia",
    role: "Admin",
    email: "olivia.garcia@example.com",
    phoneNumber: "6677889900",
    address: "606 Walnut St, Anycounty, USA",
    country: "USA",
    dob: "1983-12-05",
    gender: "female",
    documents: [],
    lastActive: "2023-06-23",
    status: "Inactive",
  },
  {
    id: 10,
    image: "https://randomuser.me/api/portraits/women/10.jpg",
    firstName: "Sophia",
    lastName: "Martinez",
    fullName: "Sophia Martinez",
    role: "User",
    email: "sophia.martinez@example.com",
    phoneNumber: "7788990011",
    address: "707 Redwood St, Anyregion, USA",
    country: "USA",
    dob: "1987-09-16",
    gender: "female",
    documents: [],
    lastActive: "2023-06-24",
    status: "Active",
  },
  {
    id: 11,
    image: "https://randomuser.me/api/portraits/men/11.jpg",
    firstName: "Lucas",
    lastName: "Miller",
    fullName: "Lucas Miller",
    role: "User",
    email: "lucas.miller@example.com",
    phoneNumber: "8899001122",
    address: "808 Cypress St, Anystate, USA",
    country: "USA",
    dob: "1993-06-11",
    gender: "male",
    documents: [],
    lastActive: "2023-06-21",
    status: "Inactive",
  },
];
